### ISSUE TITLE
metadata.fcDF.tsv not found

### ISSUE THREAD

**Issue by Chribit** [ibn-salem/chromloop_analysis#1]
Multiple scripts (e.g.: `screen_TFs_lfc.R` and `analyse_selected_models.R`) require a `metadata.fcDF.tsv` file. This file is never downloaded or created as far as I know - and it's not located anywhere else in another folder.

```
Error: 'data/ENCODE/metadata.fcDF.tsv' does not exist in current working directory ('/.../sevenC_analysis-master').
Execution halted
```

**Comment by ibn-salem** [comment]
Hi,
thanks for your interest!
The file `metadata.fcDF.tsv` is created by the script `R/filter_ENCODE.R`. 
This script is executed in the initial run of `data/download.sh` which downloads and reformats external data. 
Hope this helps!
